/-
Copyright (c) The Iris-Lean Contributors
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Iris.Algebra.StepIndex
public import Iris.Std.Classes
public meta import Iris.Std.RocqPorting

/-!
# The step-index type of this build: natural numbers

Iris uses one step-index type, `Iris.SI`, in all classes and lemmas. This file is the only file
that sets it. The repository keeps one version of this file for each supported index, in
`Iris/StepIndexChoices/<name>/StepIndexChoice.lean`. To change the index, run
`scripts/stepindex.sh <name>` (do not edit this file directly; CI checks that it is equal to a
stored version).

This version sets `SI := Nat`, as in upstream Iris-Lean. It gives the instances `SIdx SI` and
`SIdxFinite SI`.

The library uses only the `SIdx` interface of `SI` (and `SIdxFinite` where a finite index is
necessary). `SI` is a `def`, not an `abbrev`, so that the library does not see the facts of
`Nat` by accident. `SI` is the only type with an `SIdx` instance: `natSIdx` is a `def`, so that a
search for `SIdx ?I` (the index is an `outParam`) always finds `SI`.
-/

@[expose] public section

namespace Iris

/-- The step-index type of this build. -/
def SI : Type := Nat

instance instSIdxSI : SIdx SI := natSIdx

instance instSIdxFiniteSI : SIdxFinite SI := natSIdxFinite

/-- `TypeSI u` is the universe of the types that can hold a family of types in `Type u` indexed
by `SI`.

The transfinite COFE solver and `IProp` use this universe, because the solution of the domain
equation is a family of approximations indexed by `SI`. If `SI : Type v`, then `TypeSI u` must
expand to `Type (max u v)`. This is a macro and not an `abbrev`, so that the terms contain a plain
`Type`. -/
macro "TypeSI " u:level : term => `(Type $u)

/-- `levelSI% u` is the universe level of `TypeSI u`, as a term of type `Lean.Level`.

Meta code uses it, for example the HeapLang tactics. If `SI : Type v`, then `levelSI% u` must
expand to `Lean.Level.max u v`. -/
macro "levelSI% " u:term:max : term => `(($u : Lean.Level))

end Iris
