/-
Copyright (c) The Iris-Lean Contributors
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Iris.Algebra.StepIndex
public import Iris.Std.Classes
public meta import Iris.Std.RocqPorting

/-!
# The step-index type of this build: natural numbers

This file sets `Iris.SI`, the step-index type of all classes and lemmas. Each supported index has
a stored version of this file in `Iris/StepIndexChoices/<name>/`. Select one with
`scripts/stepindex.sh <name>`. Do not edit this file directly: CI checks that it is equal to a
stored version.

This version sets `SI := Nat`, as in upstream Iris-Lean, with `SIdx SI` and `SIdxFinite SI`.
-/

@[expose] public section

namespace Iris

/-- The step-index type of this build. A `def`, not an `abbrev`, so that the library uses only
the `SIdx` interface of `SI`. -/
def SI : Type := Nat

instance instSIdxSI : SIdx SI := natSIdx

instance instSIdxFiniteSI : SIdxFinite SI := natSIdxFinite

/-- `TypeSI u` is `Type (max u v)` for `SI : Type v`: the universe of the families of types in
`Type u` indexed by `SI`, such as the solution of the domain equation of `IProp`. A macro, not an
`abbrev`, so that terms contain a plain `Type`. -/
macro "TypeSI " u:level : term => `(Type $u)

/-- `levelSI% u` is the universe level of `TypeSI u`, as a term of type `Lean.Level`, for meta
code such as the HeapLang tactics. -/
macro "levelSI% " u:term:max : term => `(($u : Lean.Level))

end Iris
