/-
Copyright (c) The Iris-Lean Contributors
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Iris.Algebra.StepIndexOrdinal
public import Iris.Std.Classes
public meta import Iris.Std.RocqPorting

/-!
# The step-index type of this build: ordinals

Iris uses one step-index type, `Iris.SI`, in all classes and lemmas. This file is the only file
that sets it. The repository keeps one version of this file for each supported index, in
`Iris/StepIndexChoices/<name>/StepIndexChoice.lean`. To change the index, run
`scripts/stepindex.sh <name>` (do not edit this file directly; CI checks that it is equal to a
stored version).

This version sets `SI := Ordinals.Ordinal.{3}` (the ordinals library of this repository; no
Mathlib), so `SI : Type 4`. It gives the instances `SIdx SI`, `SIdxTransfinite SI` and
`SIdxLarge SI X` for each type `X` in `Type 0` to `Type 3`. There is no `SIdxFinite SI` instance.

The level 3 gives three levels of ordinals below the step index: `Ordinal.{0}`, `Ordinal.{1}` and
`Ordinal.{2}`. For each level `k`, `Ordinal.lift.{k, 3}` maps `Ordinal.{k}` onto an initial
segment of `SI`, and the lift of `Ordinal.univ.{k}` is above this segment. The existential
property applies to quantifiers over types in `Type 0` to `Type 3`, which include `Ordinal.{2}`.
With the instance `SIdxLarge.ulift`, it also applies to `ULift X` for these types `X`.

To use another level `n`, change `Ordinal.{3}`, `Type 4`, the `SIdxLarge` instances (one for each
`Type k` with `k ≤ n`) and the two macros. The structures of `Iris/Algebra/StepIndexOrdinal.lean`
are given for every level.
-/

@[expose] public section

noncomputable section

namespace Iris

/-- The step-index type of this build. -/
def SI : Type 4 := Ordinals.Ordinal.{3}

instance instSIdxSI : SIdx SI := ordinalSIdx

instance instSIdxTransfiniteSI : SIdxTransfinite SI := ordinalSIdxTransfinite

/-! One `SIdxLarge` instance for each universe; the instance search selects it from the type of
the quantifier. The lower levels come from level 3 through `ULift`. -/

instance instSIdxLargeSI3 {X : Type 3} : SIdxLarge SI X := ordinalSIdxLarge

instance instSIdxLargeSI2 {X : Type 2} : SIdxLarge SI X :=
  SIdxLarge.of_ulift.{_, _, 3} (h := instSIdxLargeSI3)

instance instSIdxLargeSI1 {X : Type 1} : SIdxLarge SI X :=
  SIdxLarge.of_ulift.{_, _, 3} (h := instSIdxLargeSI3)

instance instSIdxLargeSI0 {X : Type 0} : SIdxLarge SI X :=
  SIdxLarge.of_ulift.{_, _, 3} (h := instSIdxLargeSI3)

/-- `TypeSI u` is the universe of the types that can hold a family of types in `Type u` indexed
by `SI`.

The transfinite COFE solver and `IProp` use this universe, because the solution of the domain
equation is a family of approximations indexed by `SI`. `SI : Type 4`, so `TypeSI u` expands to
`Type (max u 4)`. This is a macro and not an `abbrev`, so that the terms contain a plain
`Type`. -/
macro "TypeSI " u:level : term => `(Type (max $u 4))

/-- `levelSI% u` is the universe level of `TypeSI u`, as a term of type `Lean.Level`: `max u 4`.
Meta code uses it, for example the HeapLang tactics. -/
macro "levelSI% " u:term:max : term => `(Lean.Level.max $u 4)

end Iris
