/-
Copyright (c) The Iris-Lean Contributors
Released under Apache 2.0 license as described in the file LICENSE.
-/
module

public import Iris.Algebra.StepIndexOrdinal
public import Iris.Std.Classes
public meta import Iris.Std.RocqPorting

/-!
# The step-index type of this build: ordinals

This file sets `Iris.SI`, the step-index type of all classes and lemmas. Each supported index has
a stored version of this file in `Iris/StepIndexChoices/<name>/`. Select one with
`scripts/stepindex.sh <name>`. Do not edit this file directly: CI checks that it is equal to a
stored version.

This version sets `SI := Ordinals.Ordinal.{3}`, with `SIdx SI`, `SIdxTransfinite SI` and
`SIdxLarge SI X` for each `X` in `Type 0` to `Type 3` (for example `Ordinal.{2}`). To use another
level, change `Ordinal.{3}`, `Type 4`, the `SIdxLarge` instances and the two macros.
-/

@[expose] public section

noncomputable section

namespace Iris

/-- The step-index type of this build. A `def`, not an `abbrev`, so that the library uses only
the `SIdx` interface of `SI`. -/
def SI : Type 4 := Ordinals.Ordinal.{3}

instance instSIdxSI : SIdx SI := ordinalSIdx

instance instSIdxTransfiniteSI : SIdxTransfinite SI := ordinalSIdxTransfinite

/-! One `SIdxLarge` instance for each universe. The lower levels come from level 3 through
`ULift`. -/

instance instSIdxLargeSI3 {X : Type 3} : SIdxLarge SI X := ordinalSIdxLarge

instance instSIdxLargeSI2 {X : Type 2} : SIdxLarge SI X :=
  SIdxLarge.of_ulift.{_, _, 3} (h := instSIdxLargeSI3)

instance instSIdxLargeSI1 {X : Type 1} : SIdxLarge SI X :=
  SIdxLarge.of_ulift.{_, _, 3} (h := instSIdxLargeSI3)

instance instSIdxLargeSI0 {X : Type 0} : SIdxLarge SI X :=
  SIdxLarge.of_ulift.{_, _, 3} (h := instSIdxLargeSI3)

/-- `TypeSI u` is `Type (max u v)` for `SI : Type v`: the universe of the families of types in
`Type u` indexed by `SI`, such as the solution of the domain equation of `IProp`. A macro, not an
`abbrev`, so that terms contain a plain `Type`. -/
macro "TypeSI " u:level : term => `(Type (max $u 4))

/-- `levelSI% u` is the universe level of `TypeSI u`, as a term of type `Lean.Level`, for meta
code such as the HeapLang tactics. -/
macro "levelSI% " u:term:max : term => `(Lean.Level.max $u 4)

end Iris
